apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-error
  namespace: tidb1369682775200136354
spec:
  action: error
  patterns:
    - "*"
  mode: random-max-percent
  value: "100"
  selector:
    labelSelectors:
      'app.kubernetes.io/name': 'tidb-cluster'